/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
//! `UITableView`, `UITableViewCell`.

use crate::frameworks::core_graphics::{CGPoint, CGRect, CGSize};
use crate::frameworks::foundation::{NSInteger, NSUInteger};
use crate::frameworks::uikit::ui_view;
use crate::frameworks::uikit::ui_view::ui_scroll_view::UIScrollViewHostObject;
use crate::frameworks::uikit::ui_view_controller::UIViewControllerHostObject;
use crate::objc::{
    id, impl_HostObject_with_superclass, msg, msg_class, msg_super, nil, objc_classes, release,
    retain, ClassExports, NSZonePtr,
};

#[derive(Default)]
struct UIProgressViewHostObject {
    superclass: ui_view::UIViewHostObject,
    progress: f32,
    style: i32,
    progress_tint: id,
    track_tint: id,
    progress_image: id,
    track_image: id,
}
impl_HostObject_with_superclass!(UIProgressViewHostObject);

#[derive(Default)]
struct UITableViewControllerHostObject {
    superclass: UIViewControllerHostObject,
    /// `UITableViewStyle` passed to `-initWithStyle:` (0 = plain, 1 = grouped),
    /// used by `-loadView` when it lazily creates the managed table view.
    style: i32,
}
impl_HostObject_with_superclass!(UITableViewControllerHostObject);

pub struct UITableViewCellHostObject {
    superclass: ui_view::UIViewHostObject, // <-- Убираем super::
    content_view: id,
    /// Lazily-created default subviews (UIKit's built-in cell labels/image),
    /// each retained while it lives here. `nil` until first requested.
    text_label: id,
    detail_text_label: id,
    image_view: id,
    selected: bool,
    grouped_top: bool,
    grouped_bottom: bool,
}
impl_HostObject_with_superclass!(UITableViewCellHostObject);
impl Default for UITableViewCellHostObject {
    fn default() -> Self {
        UITableViewCellHostObject {
            superclass: Default::default(),
            content_view: nil,
            text_label: nil,
            detail_text_label: nil,
            image_view: nil,
            selected: false,
            grouped_top: false,
            grouped_bottom: false,
        }
    }
}

pub struct UITableViewHostObject {
    /// Inherits all UIScrollView (and therefore UIView) state. Without this
    /// field the table view's host object would not be borrow-compatible with
    /// the superclass methods, which would route through the use-after-free
    /// fallback and corrupt rendering.
    superclass: UIScrollViewHostObject,
    /// Non-retained delegate (`UITableViewDelegate`).
    table_delegate: id,
    /// Non-retained data source (`UITableViewDataSource`).
    data_source: id,
    /// Cells currently laid out, top-to-bottom in the order generated by
    /// `reloadData`. Each cell is retained while it is in this list.
    cells: Vec<id>,
    /// Index paths matching `cells` 1:1.
    cell_index_paths: Vec<id>,
    selected_path: id,
    pressed_path: id,
    tracked_touch: id,
    touch_start: CGPoint,
    allows_selection: bool,
    style: i32,
    row_height: f32,
    section_header_height: f32,
    section_footer_height: f32,
    separator_style: NSInteger,
    separator_color: id,
    table_header_view: id,
    table_footer_view: id,
    /// Retained background view, pinned to the visible bounds.
    background_view: id,
    /// Whether we have performed the implicit first `reloadData`. UIKit
    /// reloads a table the first time it lays out with a data source; touchHLE
    /// has no automatic layout pass, so we trigger that reload ourselves the
    /// first time the table has both a data source and a non-zero size.
    auto_reloaded: bool,
}
impl Default for UITableViewHostObject {
    fn default() -> Self {
        UITableViewHostObject {
            superclass: Default::default(),
            table_delegate: nil,
            data_source: nil,
            cells: Vec::new(),
            cell_index_paths: Vec::new(),
            selected_path: nil,
            pressed_path: nil,
            tracked_touch: nil,
            touch_start: CGPoint::default(),
            allows_selection: true,
            style: 0,
            row_height: 44.0,
            section_header_height: 22.0,
            section_footer_height: 0.0,
            separator_style: 1, // UITableViewCellSeparatorStyleSingleLine
            separator_color: nil,
            table_header_view: nil,
            table_footer_view: nil,
            background_view: nil,
            auto_reloaded: false,
        }
    }
}
impl_HostObject_with_superclass!(UITableViewHostObject);

/// Perform the implicit first `reloadData` that UIKit does during a table's
/// first layout. Called whenever the data source or size changes; only fires
/// once, and only once both a data source and a usable size are available.
fn maybe_auto_reload(env: &mut crate::Environment, this: id) {
    {
        let host = env.objc.borrow::<UITableViewHostObject>(this);
        if host.auto_reloaded || host.data_source == nil {
            return;
        }
    }
    let bounds: CGRect = msg![env; this bounds];
    let (bw, bh) = (bounds.size.width, bounds.size.height);
    if bw <= 0.0 || bh <= 0.0 {
        return;
    }
    env.objc.borrow_mut::<UITableViewHostObject>(this).auto_reloaded = true;
    () = msg![env; this reloadData];
}

/// Drop the cell list and (optionally) remove the cell views from the table.
fn clear_cells(env: &mut crate::Environment, this: id, remove_subviews: bool) {
    let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
    let selected = std::mem::replace(&mut host.selected_path, nil);
    let pressed = std::mem::replace(&mut host.pressed_path, nil);
    host.tracked_touch = nil;
    release(env, selected);
    release(env, pressed);
    // Take both vectors out so we can release without nested borrows.
    let (cells, paths) = {
        let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
        (
            std::mem::take(&mut host.cells),
            std::mem::take(&mut host.cell_index_paths),
        )
    };
    for cell in cells {
        if remove_subviews {
            let _: () = msg![env; cell removeFromSuperview];
        }
        release(env, cell);
    }
    for path in paths {
        release(env, path);
    }
}

fn make_rect(x: f32, y: f32, w: f32, h: f32) -> CGRect {
    CGRect {
        origin: CGPoint { x, y },
        size: CGSize { width: w, height: h },
    }
}

/// Position a `UITableViewCell`'s built-in content view, image view and text
/// labels, mirroring UIKit's default cell layout closely enough to be
/// recognisable: the optional image sits on the left and the text label fills
/// the remaining width. touchHLE has no automatic layout pass, so this is
/// invoked whenever the cell's frame changes or a default subview is created.
fn layout_cell_contents(env: &mut crate::Environment, this: id) {
    let bounds: CGRect = msg![env; this bounds];
    let (w, h) = (bounds.size.width, bounds.size.height);
    let (content_view, image_view, text_label, detail_label) = {
        let host = env.objc.borrow::<UITableViewCellHostObject>(this);
        (
            host.content_view,
            host.image_view,
            host.text_label,
            host.detail_text_label,
        )
    };

    if content_view != nil {
        () = msg![env; content_view setFrame:(make_rect(0.0, 0.0, w, h))];
    }

    let mut text_x = 10.0;
    if image_view != nil {
        let image: id = msg![env; image_view image];
        if image != nil && h > 0.0 {
            () = msg![env; image_view setFrame:(make_rect(0.0, 0.0, h, h))];
            text_x = h + 10.0;
        } else {
            () = msg![env; image_view setFrame:(make_rect(0.0, 0.0, 0.0, 0.0))];
        }
    }

    let text_w = (w - text_x - 10.0).max(0.0);
    if text_label != nil && detail_label != nil {
        // Two-line cell: stack the title over the detail text.
        () = msg![env; text_label setFrame:(make_rect(text_x, 0.0, text_w, h * 0.6))];
        () = msg![env; detail_label setFrame:(make_rect(text_x, h * 0.6, text_w, h * 0.4))];
    } else if text_label != nil {
        () = msg![env; text_label setFrame:(make_rect(text_x, 0.0, text_w, h))];
    }
}

/// Lazily create one of the cell's default subviews (a `UILabel` or
/// `UIImageView`) with a transparent background so the cell shows through,
/// add it to the content view, and store it in `slot`.
fn ensure_cell_subview(env: &mut crate::Environment, this: id, class_name: &str) -> id {
    let content_view = env.objc.borrow::<UITableViewCellHostObject>(this).content_view;
    let class = env.objc.get_known_class(class_name, &mut env.mem);
    let view: id = msg![env; class alloc];
    let view: id = msg![env; view init];
    let clear: id = msg_class![env; UIColor clearColor];
    () = msg![env; view setBackgroundColor:clear];
    retain(env, view);
    if content_view != nil {
        () = msg![env; content_view addSubview:view];
    }
    view
}

pub const CLASSES: ClassExports = objc_classes! {

(env, this, _cmd);

// Добавляем приватный класс, на который ругается NIB-декодер
@implementation UITableViewCellContentView: UIView

- (id)initWithFrame:(CGRect)frame {
    msg_super![env; this initWithFrame:frame]
}

- (id)initWithCoder:(id)coder {
    msg_super![env; this initWithCoder:coder]
}

@end

@implementation UITableViewCell: UIView

+ (id)allocWithZone:(NSZonePtr)_zone {
    let host_object = Box::<UITableViewCellHostObject>::default();
    env.objc.alloc_object(this, host_object, &mut env.mem)
}

- (())drawRect:(CGRect)_rect {
    use ui_view::ios5_theme::{fill_solid, rgb};
    let ctx = crate::frameworks::uikit::ui_graphics::UIGraphicsGetCurrentContext(env);
    if ctx == nil { return; }
    let bounds: CGRect = msg![env; this bounds];
    let host = env.objc.borrow::<UITableViewCellHostObject>(this);
    let (selected, top, bottom) = (host.selected, host.grouped_top, host.grouped_bottom);
    let parent: id = msg![env; this superview];
    let class = env.objc.get_known_class("UITableView", &mut env.mem);
    let in_table: bool = msg![env; parent isKindOfClass:class];
    let mut separator = true;
    let mut edge = rgb(0xB8BEC5);
    if in_table {
        let style: i32 = msg![env; parent separatorStyle];
        separator = style != 0;
        let color: id = msg![env; parent separatorColor];
        if color != nil { edge = crate::frameworks::uikit::ui_color::get_rgba(&env.objc, color); }
    }
    let bg: id = msg![env; this backgroundColor];
    let normal = if bg == nil { rgb(0xF7F7F7) }
        else { crate::frameworks::uikit::ui_color::get_rgba(&env.objc, bg) };
    let h = bounds.size.height;
    let r = 8.0f32.min(bounds.size.width / 2.0).min(h / 2.0).max(0.0);
    for i in 0..(h * 2.0).ceil() as i32 {
        let y = i as f32 * 0.5;
        let cy = y + 0.25;
        let distance = if top && cy < r { r - cy }
            else if bottom && cy > h - r { cy - (h - r) } else { 0.0 };
        let inset = r - (r * r - distance * distance).max(0.0).sqrt();
        let mut strip = CGRect {
            origin: CGPoint { x: bounds.origin.x + inset, y: bounds.origin.y + y },
            size: CGSize { width: (bounds.size.width - 2.0 * inset).max(0.0), height: (h - y).min(0.5) },
        };
        if separator || top || bottom { fill_solid(env, ctx, strip, edge); }
        if (top && y < 0.5) || ((separator || bottom) && y + 0.5 >= h) { continue; }
        if top || bottom {
            strip.origin.x += 0.5;
            strip.size.width = (strip.size.width - 1.0).max(0.0);
        }
        let t = cy / h.max(1.0);
        let color = if selected {
            let a = rgb(0x278AF2);
            let b = rgb(0x405F8A);
            (a.0 + (b.0 - a.0) * t, a.1 + (b.1 - a.1) * t,
             a.2 + (b.2 - a.2) * t, 1.0)
        } else { normal };
        fill_solid(env, ctx, strip, color);
    }
}

- (id)initWithFrame:(CGRect)frame {
    let this: id = msg_super![env; this initWithFrame:frame];

    // Честно создаем внутренний content_view.
    // Передаем имя класса напрямую в макрос msg_class!
    let content_view: id = msg_class![env; UITableViewCellContentView alloc];
    let content_view: id = msg![env; content_view initWithFrame:frame];

    // Добавляем его как subview (как в iOS)
    () = msg![env; this addSubview:content_view];

    env.objc.borrow_mut::<UITableViewCellHostObject>(this).content_view = content_view;
    this
}

- (id)initWithStyle:(i32)_style reuseIdentifier:(id)_identifier {
    let frame = <CGRect as Default>::default();
    msg![env; this initWithFrame:frame]
}

// `-[UITableViewCell initWithFrame:reuseIdentifier:]` is the iOS 2.x
// designated initializer, deprecated in iOS 3.0 in favour of
// `-initWithStyle:reuseIdentifier:`. The header (UIKit's
// `UITableViewCell.h`) still ships the symbol, and several legacy 32-bit
// games (e.g. Cooking Fever, Dungeon Shooter) call it. Apple's reference
// implementation routes it through the frame-only initializer and
// records the reuse identifier — the reuse identifier itself is held by
// the cell so that `+[UITableView dequeueReusableCellWithIdentifier:]`
// can later match it. <https://developer.apple.com/documentation/uikit/uitableviewcell/1623200-initwithframe>
- (id)initWithFrame:(CGRect)frame reuseIdentifier:(id)_identifier {
    msg![env; this initWithFrame:frame]
}

- (id)initWithCoder:(id)coder {
    let this: id = msg_super![env; this initWithCoder:coder];
    // При загрузке из NIB contentView обычно уже внутри (как под-вьюха).
    // Мы можем просто инициализировать поле, если NIB его создал,
    // но для безопасности создадим пустой, если его нет.
    let frame = <CGRect as Default>::default();

    // Исправлено здесь: убран get_known_class и переменная, имя класса передано
    // напрямую
    let content_view: id = msg_class![env; UITableViewCellContentView alloc];
    let content_view: id = msg![env; content_view initWithFrame:frame];

    () = msg![env; this addSubview:content_view];
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).content_view = content_view;
    this
}

- (())dealloc {
    let (content_view, text_label, detail_label, image_view) = {
        let host = env.objc.borrow::<UITableViewCellHostObject>(this);
        (host.content_view, host.text_label, host.detail_text_label, host.image_view)
    };
    release(env, content_view);
    if text_label != nil { release(env, text_label); }
    if detail_label != nil { release(env, detail_label); }
    if image_view != nil { release(env, image_view); }
    msg_super![env; this dealloc]
}

- (id)reuseIdentifier { nil }

- (id)textLabel {
    let existing = env.objc.borrow::<UITableViewCellHostObject>(this).text_label;
    if existing != nil {
        return existing;
    }
    let label = ensure_cell_subview(env, this, "UILabel");
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).text_label = label;
    layout_cell_contents(env, this);
    label
}

- (id)detailTextLabel {
    let existing = env.objc.borrow::<UITableViewCellHostObject>(this).detail_text_label;
    if existing != nil {
        return existing;
    }
    let label = ensure_cell_subview(env, this, "UILabel");
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).detail_text_label = label;
    layout_cell_contents(env, this);
    label
}

- (id)imageView {
    let existing = env.objc.borrow::<UITableViewCellHostObject>(this).image_view;
    if existing != nil {
        return existing;
    }
    let iv = ensure_cell_subview(env, this, "UIImageView");
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).image_view = iv;
    layout_cell_contents(env, this);
    iv
}

- (())setFrame:(CGRect)frame {
    () = msg_super![env; this setFrame:frame];
    layout_cell_contents(env, this);
}

- (())layoutSubviews {
    () = msg_super![env; this layoutSubviews];
    layout_cell_contents(env, this);
}

// Теперь возвращаем реальный contentView, а не this
- (id)contentView {
    env.objc.borrow::<UITableViewCellHostObject>(this).content_view
}

- (id)accessoryView { nil }
- (())setAccessoryView:(id)_view {}
- (i32)accessoryType { 0 }
- (())setAccessoryType:(i32)_type {}
- (i32)selectionStyle { 0 }
- (())setSelectionStyle:(i32)_style {}
- (bool)isSelected {
    env.objc.borrow::<UITableViewCellHostObject>(this).selected
}
- (())setSelected:(bool)selected {
    () = msg![env; this setSelected:selected animated:false];
}
- (())setSelected:(bool)selected animated:(bool)_animated {
    let host = env.objc.borrow_mut::<UITableViewCellHostObject>(this);
    host.selected = selected;
    let labels = [host.text_label, host.detail_text_label];
    for label in labels { () = msg![env; label setHighlighted:selected]; }
    () = msg![env; this setNeedsDisplay];
}
- (bool)isHighlighted { false }
- (())setHighlighted:(bool)_highlighted {}
- (())setHighlighted:(bool)_highlighted animated:(bool)_animated {}
- (())prepareForReuse {}
- (id)backgroundView { nil }
- (())setBackgroundView:(id)_view {}
- (id)selectedBackgroundView { nil }
- (())setSelectedBackgroundView:(id)_view {}
- (())setEditing:(bool)_editing animated:(bool)_animated {}
- (bool)isEditing { false }
- (i32)editingStyle { 0 }
- (bool)showingDeleteConfirmation { false }
- (())setIndentationLevel:(i32)_level {}
- (i32)indentationLevel { 0 }

@end

@implementation UIProgressView: UIView

+ (id)allocWithZone:(NSZonePtr)_zone {
    env.objc.alloc_object(this, Box::<UIProgressViewHostObject>::default(), &mut env.mem)
}

- (())layoutSubviews {
    () = msg_super![env; this layoutSubviews];
    () = msg![env; this setNeedsDisplay];
}

- (())drawRect:(CGRect)_rect {
    use ui_view::ios5_theme::{draw_recessed_track, draw_surface, inset_rect, rgb};
    let ctx = crate::frameworks::uikit::ui_graphics::UIGraphicsGetCurrentContext(env);
    let bounds: CGRect = msg![env; this bounds];
    let host = env.objc.borrow::<UIProgressViewHostObject>(this);
    let (progress, style, tint, track_tint, image, track_image) = (
        host.progress, host.style, host.progress_tint, host.track_tint,
        host.progress_image, host.track_image,
    );
    let height = bounds.size.height.min(if style == 1 { 7.0 } else { 9.0 }).max(0.0);
    let track = CGRect {
        origin: CGPoint { x: bounds.origin.x, y: bounds.origin.y + (bounds.size.height - height) / 2.0 },
        size: CGSize { width: bounds.size.width, height },
    };
    if track_image != nil { () = msg![env; track_image drawInRect:track]; }
    else {
        let color = if track_tint == nil { rgb(0xC4C4C7) } else {
            crate::frameworks::uikit::ui_color::get_rgba(&env.objc, track_tint)
        };
        draw_recessed_track(env, ctx, track, color, height / 2.0);
    }
    let mut fill = inset_rect(track, 1.0, 1.0);
    fill.size.width *= progress;
    if image != nil { () = msg![env; image drawInRect:fill]; }
    else {
        let top = if tint == nil { rgb(0x278AF2) } else {
            crate::frameworks::uikit::ui_color::get_rgba(&env.objc, tint)
        };
        let bottom = if tint == nil { rgb(0x3EC9FB) } else {
            ui_view::ios5_theme::scale_brightness(top, 1.15)
        };
        draw_surface(env, ctx, fill, height / 2.0,
            &[(0.0, top), (1.0, bottom)], rgb(0x405F8A));
    }
}

- (())dealloc {
    let host = env.objc.borrow::<UIProgressViewHostObject>(this);
    let refs = [host.progress_tint, host.track_tint, host.progress_image, host.track_image];
    for obj in refs { release(env, obj); }
    msg_super![env; this dealloc]
}

- (id)initWithFrame:(CGRect)frame {
    msg_super![env; this initWithFrame:frame]
}

- (id)initWithProgressViewStyle:(i32)style {
    let this: id = msg![env; this initWithFrame:(CGRect {
        origin: CGPoint::default(), size: CGSize { width: 150.0, height: 9.0 },
    })];
    () = msg![env; this setProgressViewStyle:style];
    this
}

- (f32)progress { env.objc.borrow::<UIProgressViewHostObject>(this).progress }
- (())setProgress:(f32)value {
    env.objc.borrow_mut::<UIProgressViewHostObject>(this).progress =
        if value.is_finite() { value.clamp(0.0, 1.0) } else { 0.0 };
    () = msg![env; this setNeedsDisplay];
}
- (())setProgress:(f32)value animated:(bool)_animated { () = msg![env; this setProgress:value]; }
- (i32)progressViewStyle { env.objc.borrow::<UIProgressViewHostObject>(this).style }
- (())setProgressViewStyle:(i32)style {
    env.objc.borrow_mut::<UIProgressViewHostObject>(this).style = style;
    () = msg![env; this setNeedsDisplay];
}
- (id)progressTintColor { env.objc.borrow::<UIProgressViewHostObject>(this).progress_tint }
- (())setProgressTintColor:(id)color {
    retain(env, color);
    let old = std::mem::replace(&mut env.objc.borrow_mut::<UIProgressViewHostObject>(this).progress_tint, color);
    release(env, old);
    () = msg![env; this setNeedsDisplay];
}
- (id)trackTintColor { env.objc.borrow::<UIProgressViewHostObject>(this).track_tint }
- (())setTrackTintColor:(id)color {
    retain(env, color);
    let old = std::mem::replace(&mut env.objc.borrow_mut::<UIProgressViewHostObject>(this).track_tint, color);
    release(env, old);
    () = msg![env; this setNeedsDisplay];
}
- (id)progressImage { env.objc.borrow::<UIProgressViewHostObject>(this).progress_image }
- (())setProgressImage:(id)image {
    retain(env, image);
    let old = std::mem::replace(&mut env.objc.borrow_mut::<UIProgressViewHostObject>(this).progress_image, image);
    release(env, old);
    () = msg![env; this setNeedsDisplay];
}
- (id)trackImage { env.objc.borrow::<UIProgressViewHostObject>(this).track_image }
- (())setTrackImage:(id)image {
    retain(env, image);
    let old = std::mem::replace(&mut env.objc.borrow_mut::<UIProgressViewHostObject>(this).track_image, image);
    release(env, old);
    () = msg![env; this setNeedsDisplay];
}

@end

@implementation UITableView: UIScrollView

+ (id)allocWithZone:(NSZonePtr)_zone {
    let host_object = Box::<UITableViewHostObject>::default();
    env.objc.alloc_object(this, host_object, &mut env.mem)
}

- (id)initWithFrame:(CGRect)frame style:(i32)style {
    env.objc.borrow_mut::<UITableViewHostObject>(this).style = style;
    let this: id = msg_super![env; this initWithFrame:frame];
    () = msg![env; this setNeedsDisplay];
    this
}

- (i32)style { env.objc.borrow::<UITableViewHostObject>(this).style }

- (())drawRect:(CGRect)_rect {
    use ui_view::ios5_theme::{fill_solid, rgb};
    let ctx = crate::frameworks::uikit::ui_graphics::UIGraphicsGetCurrentContext(env);
    let host = env.objc.borrow::<UITableViewHostObject>(this);
    if host.background_view != nil { return; }
    let style = host.style;
    let bounds: CGRect = msg![env; this bounds];
    let bg: id = msg![env; this backgroundColor];
    let color = if bg != nil {
        crate::frameworks::uikit::ui_color::get_rgba(&env.objc, bg)
    } else if style == 1 { rgb(0xD6DDE2) } else { rgb(0xFFFFFF) };
    fill_solid(env, ctx, bounds, color);
    if bg == nil && style == 1 {
        ui_view::ios5_theme::draw_grouped_texture(env, ctx, bounds);
    }
}

- (())dealloc {
    clear_cells(env, this, false);
    let header = env.objc.borrow::<UITableViewHostObject>(this).table_header_view;
    let footer = env.objc.borrow::<UITableViewHostObject>(this).table_footer_view;
    let separator_color = env.objc.borrow::<UITableViewHostObject>(this).separator_color;
    if header != nil { release(env, header); }
    if footer != nil { release(env, footer); }
    if separator_color != nil { release(env, separator_color); }
    let background = env.objc.borrow::<UITableViewHostObject>(this).background_view;
    release(env, background);
    msg_super![env; this dealloc]
}

- (id)backgroundView {
    env.objc.borrow::<UITableViewHostObject>(this).background_view
}

- (())setBackgroundView:(id)view {
    let old = env.objc.borrow::<UITableViewHostObject>(this).background_view;
    if old == view {
        return;
    }
    retain(env, view);
    env.objc.borrow_mut::<UITableViewHostObject>(this).background_view = view;
    if old != nil {
        () = msg![env; old removeFromSuperview];
        release(env, old);
    }
    if view != nil {
        let bounds: CGRect = msg![env; this bounds];
        () = msg![env; view setFrame:bounds];
        () = msg![env; this insertSubview:view atIndex:(0 as NSInteger)];
    }
}

- (id)visibleCells {
    // We don't track visibility separately from layout, so report every cell
    // currently materialised by -reloadData.
    let cells = env.objc.borrow::<UITableViewHostObject>(this).cells.clone();
    let array: id = msg_class![env; NSMutableArray array];
    for cell in cells {
        () = msg![env; array addObject:cell];
    }
    array
}

- (id)delegate {
    env.objc.borrow::<UITableViewHostObject>(this).table_delegate
}
- (())setDelegate:(id)delegate {
    env.objc.borrow_mut::<UITableViewHostObject>(this).table_delegate = delegate;
}
- (id)dataSource {
    env.objc.borrow::<UITableViewHostObject>(this).data_source
}
- (())setDataSource:(id)data_source {
    env.objc.borrow_mut::<UITableViewHostObject>(this).data_source = data_source;
    maybe_auto_reload(env, this);
}

- (())setFrame:(CGRect)frame {
    () = msg_super![env; this setFrame:frame];
    let background = env.objc.borrow::<UITableViewHostObject>(this).background_view;
    if background != nil {
        let bounds: CGRect = msg![env; this bounds];
        () = msg![env; background setFrame:bounds];
    }
    maybe_auto_reload(env, this);
}

- (())setBounds:(CGRect)bounds {
    () = msg_super![env; this setBounds:bounds];
    let background = env.objc.borrow::<UITableViewHostObject>(this).background_view;
    if background != nil {
        let bounds: CGRect = msg![env; this bounds];
        () = msg![env; background setFrame:bounds];
    }
    maybe_auto_reload(env, this);
}

- (())layoutSubviews {
    () = msg_super![env; this layoutSubviews];
    let background = env.objc.borrow::<UITableViewHostObject>(this).background_view;
    if background != nil {
        let bounds: CGRect = msg![env; this bounds];
        () = msg![env; background setFrame:bounds];
        () = msg![env; this sendSubviewToBack:background];
    }
}

- (())reloadData {
    // Drop existing cells before recreating them.
    clear_cells(env, this, true);

    let data_source = env.objc.borrow::<UITableViewHostObject>(this).data_source;
    if data_source == nil {
        return;
    }

    let bounds: CGRect = msg![env; this bounds];
    let width = bounds.size.width;
    let row_height = env.objc.borrow::<UITableViewHostObject>(this).row_height;

    // Section count defaults to 1 if the data source does not implement
    // -numberOfSectionsInTableView:.
    let sel_num_sections = env.objc.lookup_selector("numberOfSectionsInTableView:");
    let mut num_sections: NSInteger = 1;
    if let Some(sel) = sel_num_sections {
        let responds: bool = msg![env; data_source respondsToSelector:sel];
        if responds {
            num_sections = msg![env; data_source numberOfSectionsInTableView:this];
        }
    }

    let mut y: f32 = 0.0;
    let header = env.objc.borrow::<UITableViewHostObject>(this).table_header_view;
    if header != nil {
        let mut frame: CGRect = msg![env; header frame];
        let h = frame.size.height.max(0.0);
        frame.origin = CGPoint { x: 0.0, y };
        frame.size.width = width;
        () = msg![env; header setFrame:frame];
        () = msg![env; this addSubview:header];
        y += h;
    }

    let mut new_cells: Vec<id> = Vec::new();
    let mut new_paths: Vec<id> = Vec::new();

    for section in 0..num_sections {
        let row_count: NSInteger = msg![env; data_source
            tableView:this
            numberOfRowsInSection:section];
        if row_count > 0 && env.objc.borrow::<UITableViewHostObject>(this).style == 1 {
            y += 20.0;
        }
        for row in 0..row_count {
            let index_path: id = msg_class![env; NSIndexPath
                indexPathForRow:(row as NSUInteger)
                inSection:(section as NSUInteger)];
            retain(env, index_path);

            let cell: id = msg![env; data_source
                tableView:this
                cellForRowAtIndexPath:index_path];
            if cell == nil {
                release(env, index_path);
                continue;
            }
            retain(env, cell);

            let grouped = env.objc.borrow::<UITableViewHostObject>(this).style == 1;
            let inset = if grouped { 10.0 } else { 0.0 };
            let frame = CGRect {
                origin: CGPoint { x: inset, y },
                size: CGSize { width: (width - 2.0 * inset).max(0.0), height: row_height },
            };
            let host = env.objc.borrow_mut::<UITableViewCellHostObject>(cell);
            host.grouped_top = grouped && row == 0;
            host.grouped_bottom = grouped && row == row_count - 1;
            () = msg![env; cell setFrame:frame];
            () = msg![env; this addSubview:cell];
            () = msg![env; cell setNeedsDisplay];

            y += row_height;
            new_cells.push(cell);
            new_paths.push(index_path);
        }
    }

    let footer = env.objc.borrow::<UITableViewHostObject>(this).table_footer_view;
    if footer != nil {
        let mut frame: CGRect = msg![env; footer frame];
        let h = frame.size.height.max(0.0);
        frame.origin = CGPoint { x: 0.0, y };
        frame.size.width = width;
        () = msg![env; footer setFrame:frame];
        () = msg![env; this addSubview:footer];
        y += h;
    }

    {
        let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
        host.cells = new_cells;
        host.cell_index_paths = new_paths;
    }

    let content_size = CGSize { width, height: y };
    () = msg![env; this setContentSize:content_size];
}

- (())reloadSections:(id)_sections withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}
- (())reloadRowsAtIndexPaths:(id)_paths withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}
- (i32)numberOfSections {
    let data_source = env.objc.borrow::<UITableViewHostObject>(this).data_source;
    if data_source == nil { return 0; }
    let sel = match env.objc.lookup_selector("numberOfSectionsInTableView:") {
        Some(sel) => sel,
        None => return 1,
    };
    let responds: bool = msg![env; data_source respondsToSelector:sel];
    if !responds { return 1; }
    msg![env; data_source numberOfSectionsInTableView:this]
}
- (i32)numberOfRowsInSection:(i32)section {
    let data_source = env.objc.borrow::<UITableViewHostObject>(this).data_source;
    if data_source == nil { return 0; }
    msg![env; data_source tableView:this numberOfRowsInSection:section]
}
- (id)indexPathForRowAtPoint:(CGPoint)point {
    let cells = env.objc.borrow::<UITableViewHostObject>(this).cells.clone();
    for (i, cell) in cells.into_iter().enumerate() {
        let frame: CGRect = msg![env; cell frame];
        if point.x >= frame.origin.x && point.y >= frame.origin.y
            && point.x < frame.origin.x + frame.size.width
            && point.y < frame.origin.y + frame.size.height {
            return env.objc.borrow::<UITableViewHostObject>(this).cell_index_paths[i];
        }
    }
    nil
}

- (())touchesBegan:(id)touches withEvent:(id)_event {
    let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
    let was_tracking = host.tracked_touch != nil;
    let old = std::mem::replace(&mut host.pressed_path, nil);
    host.tracked_touch = nil;
    release(env, old);
    let count: NSUInteger = msg![env; touches count];
    let allows: bool = msg![env; this allowsSelection];
    if was_tracking || count != 1 || !allows { return; }
    let touch: id = msg![env; touches anyObject];
    let point: CGPoint = msg![env; touch locationInView:this];
    let start: CGPoint = msg![env; touch locationInView:nil];
    let path: id = msg![env; this indexPathForRowAtPoint:point];
    retain(env, path);
    let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
    host.pressed_path = path;
    host.tracked_touch = touch;
    host.touch_start = start;
}

- (())touchesMoved:(id)touches withEvent:(id)event {
    let host = env.objc.borrow::<UITableViewHostObject>(this);
    let (touch, start) = (host.tracked_touch, host.touch_start);
    if touch != nil {
        let point: CGPoint = msg![env; touch locationInView:nil];
        if (point.x - start.x).hypot(point.y - start.y) > 8.0 {
            let old = std::mem::replace(
                &mut env.objc.borrow_mut::<UITableViewHostObject>(this).pressed_path, nil,
            );
            release(env, old);
        }
    }
    () = msg_super![env; this touchesMoved:touches withEvent:event];
}

- (())touchesCancelled:(id)touches withEvent:(id)event {
    let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
    let old = std::mem::replace(&mut host.pressed_path, nil);
    host.tracked_touch = nil;
    release(env, old);
    () = msg_super![env; this touchesCancelled:touches withEvent:event];
}

- (())touchesEnded:(id)touches withEvent:(id)event {
    let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
    let path = std::mem::replace(&mut host.pressed_path, nil);
    let touch = std::mem::replace(&mut host.tracked_touch, nil);
    let start = host.touch_start;
    () = msg_super![env; this touchesEnded:touches withEvent:event];
    let allows: bool = msg![env; this allowsSelection];
    let ended: bool = msg![env; touches containsObject:touch];
    if path != nil && touch != nil && ended && allows {
        let point: CGPoint = msg![env; touch locationInView:this];
        let end: CGPoint = msg![env; touch locationInView:nil];
        let hit: id = msg![env; this indexPathForRowAtPoint:point];
        let same: bool = msg![env; path isEqual:hit];
        if same && (end.x - start.x).hypot(end.y - start.y) <= 8.0 {
            let delegate: id = msg![env; this delegate];
            let sel = env.objc.register_host_selector(
                "tableView:willSelectRowAtIndexPath:".into(), &mut env.mem,
            );
            let responds: bool = msg![env; delegate respondsToSelector:sel];
            let selected: id = if responds {
                msg![env; delegate tableView:this willSelectRowAtIndexPath:path]
            } else { path };
            if selected != nil {
                retain(env, selected);
                () = msg![env; this selectRowAtIndexPath:selected animated:false scrollPosition:0i32];
                let sel = env.objc.register_host_selector(
                    "tableView:didSelectRowAtIndexPath:".into(), &mut env.mem,
                );
                let responds: bool = msg![env; delegate respondsToSelector:sel];
                if responds {
                    () = msg![env; delegate tableView:this didSelectRowAtIndexPath:selected];
                }
                release(env, selected);
            }
        }
    }
    release(env, path);
}

- (id)cellForRowAtIndexPath:(id)path {
    if path == nil { return nil; }
    let cell_paths = env.objc.borrow::<UITableViewHostObject>(this).cell_index_paths.clone();
    for (i, other) in cell_paths.into_iter().enumerate() {
        let equal: bool = msg![env; path isEqual:other];
        if equal {
            return env.objc.borrow::<UITableViewHostObject>(this).cells[i];
        }
    }
    nil
}
- (id)dequeueReusableCellWithIdentifier:(id)_identifier {
    // We don't keep a reuse pool; returning nil forces the data source to
    // create a fresh cell, which is always valid per Apple's API.
    nil
}
- (id)indexPathForCell:(id)cell {
    if cell == nil { return nil; }
    let host = env.objc.borrow::<UITableViewHostObject>(this);
    for (i, &c) in host.cells.iter().enumerate() {
        if c == cell {
            return host.cell_index_paths[i];
        }
    }
    nil
}
- (id)indexPathForSelectedRow {
    env.objc.borrow::<UITableViewHostObject>(this).selected_path
}
- (id)indexPathsForSelectedRows {
    let path: id = msg![env; this indexPathForSelectedRow];
    if path == nil { return nil; }
    msg_class![env; NSArray arrayWithObject:path]
}
- (())selectRowAtIndexPath:(id)path animated:(bool)animated scrollPosition:(i32)_pos {
    if path != nil {
        let cell: id = msg![env; this cellForRowAtIndexPath:path];
        if cell == nil { return; }
    }
    retain(env, path);
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).selected_path, path,
    );
    let old_cell: id = msg![env; this cellForRowAtIndexPath:old];
    () = msg![env; old_cell setSelected:false animated:animated];
    let cell: id = msg![env; this cellForRowAtIndexPath:path];
    () = msg![env; cell setSelected:true animated:animated];
    release(env, old);
}
- (())deselectRowAtIndexPath:(id)path animated:(bool)animated {
    let selected: id = msg![env; this indexPathForSelectedRow];
    let equal: bool = msg![env; selected isEqual:path];
    if equal {
        () = msg![env; this selectRowAtIndexPath:nil animated:animated scrollPosition:0i32];
    }
}
- (())scrollToRowAtIndexPath:(id)_path atScrollPosition:(i32)_pos animated:(bool)_animated {}
- (())setEditing:(bool)_editing animated:(bool)_animated {}
- (bool)isEditing { false }
- (())setAllowsSelection:(bool)allows {
    env.objc.borrow_mut::<UITableViewHostObject>(this).allows_selection = allows;
}
- (bool)allowsSelection {
    env.objc.borrow::<UITableViewHostObject>(this).allows_selection
}
- (())setAllowsMultipleSelection:(bool)_allows {}
- (())setRowHeight:(f32)height {
    env.objc.borrow_mut::<UITableViewHostObject>(this).row_height = height;
}
- (f32)rowHeight {
    env.objc.borrow::<UITableViewHostObject>(this).row_height
}
- (())setSectionHeaderHeight:(f32)height {
    env.objc.borrow_mut::<UITableViewHostObject>(this).section_header_height = height;
}
- (())setSectionFooterHeight:(f32)height {
    env.objc.borrow_mut::<UITableViewHostObject>(this).section_footer_height = height;
}
- (id)tableHeaderView {
    env.objc.borrow::<UITableViewHostObject>(this).table_header_view
}
- (())setTableHeaderView:(id)view {
    if view != nil { retain(env, view); }
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).table_header_view,
        view,
    );
    if old != nil { release(env, old); }
}
- (id)tableFooterView {
    env.objc.borrow::<UITableViewHostObject>(this).table_footer_view
}
- (())setTableFooterView:(id)view {
    if view != nil { retain(env, view); }
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).table_footer_view,
        view,
    );
    if old != nil { release(env, old); }
}
- (())setSeparatorStyle:(i32)style {
    env.objc.borrow_mut::<UITableViewHostObject>(this).separator_style = style as NSInteger;
}
- (i32)separatorStyle {
    env.objc.borrow::<UITableViewHostObject>(this).separator_style
}
- (())setSeparatorColor:(id)color {
    if color != nil { retain(env, color); }
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).separator_color,
        color,
    );
    if old != nil { release(env, old); }
}
- (id)separatorColor {
    env.objc.borrow::<UITableViewHostObject>(this).separator_color
}
- (())registerClass:(id)_class forCellReuseIdentifier:(id)_identifier {}
- (())registerNib:(id)_nib forCellReuseIdentifier:(id)_identifier {}
- (())beginUpdates {}
- (())endUpdates {}
- (())insertRowsAtIndexPaths:(id)_paths withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}
- (())deleteRowsAtIndexPaths:(id)_paths withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}

@end

@implementation UITableViewController: UIViewController

+ (id)allocWithZone:(NSZonePtr)_zone {
    let host_object = Box::<UITableViewControllerHostObject>::default();
    env.objc.alloc_object(this, host_object, &mut env.mem)
}

- (id)initWithStyle:(i32)style {
    let this: id = msg_super![env; this init];
    env.objc.borrow_mut::<UITableViewControllerHostObject>(this).style = style;
    this
}

// Честный iOS-подход: переопределяем создание вьюхи по умолчанию.
// Если NIB'а нет, мы принудительно создаем UITableView, а не UIView.
- (())loadView {
    let frame = <CGRect as Default>::default();
    let style = env.objc.borrow::<UITableViewControllerHostObject>(this).style;
    let table_view: id = msg_class![env; UITableView alloc];
    let table_view: id = msg![env; table_view initWithFrame:frame style:style];

    // UITableViewController owns its table view and, per UIKit, makes itself
    // both the data source and the delegate. Without this the table never asks
    // the controller for any rows and renders empty (a blank white screen).
    () = msg![env; table_view setDataSource:this];
    () = msg![env; table_view setDelegate:this];

    // Устанавливаем таблицу как главную view этого контроллера
    () = msg![env; this setView:table_view];
    release(env, table_view);
}

// Теперь tableView ссылается на реальный UITableView
- (id)tableView {
    msg![env; this view]
}

- (())setTableView:(id)view {
    () = msg![env; this setView:view];
}

- (bool)clearsSelectionOnViewWillAppear { true }
- (())setClearsSelectionOnViewWillAppear:(bool)_clears {}

@end

};